Bag of words

In [1]:
import numpy as np
import pandas as pd

In [3]:
df = pd.DataFrame({
    'text': [
        'people watch campusx',
        'campusx watch campusx',
        'people write comment',
        'campusx write comment'
    ],
    'output': [1, 1, 0, 0]
})
df

,text,output
0,people watch campusx,1
1,campusx watch campusx,1
2,people write comment,0
3,campusx write comment,0


In [5]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer()

In [ ]:
bow=cv.fit_transform(df['text'])

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 11 stored elements and shape (4, 5)>

In [8]:
# Vocabulary
print(cv.vocabulary_)

{'people': 2, 'watch': 3, 'campusx': 0, 'write': 4, 'comment': 1}


In [9]:
print(bow.toarray())

[[1 0 1 1 0]
 [2 0 0 1 0]
 [0 1 1 0 1]
 [1 1 0 0 1]]


N-grams

In [16]:
cv=CountVectorizer(ngram_range=(1, 3))

In [17]:
bow=cv.fit_transform(df['text'])

In [18]:
# Vocabulary
print(cv.vocabulary_)

{'people': 6, 'watch': 11, 'campusx': 0, 'people watch': 7, 'watch campusx': 12, 'people watch campusx': 8, 'campusx watch': 1, 'campusx watch campusx': 2, 'write': 13, 'comment': 5, 'people write': 9, 'write comment': 14, 'people write comment': 10, 'campusx write': 3, 'campusx write comment': 4}


In [19]:
print(len(cv.vocabulary_))

15


In [20]:
print(bow.toarray())

[[1 0 0 0 0 0 1 1 1 0 0 1 1 0 0]
 [2 1 1 0 0 0 0 0 0 0 0 1 1 0 0]
 [0 0 0 0 0 1 1 0 0 1 1 0 0 1 1]
 [1 0 0 1 1 1 0 0 0 0 0 0 0 1 1]]


Tf-Idf

In [22]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf=TfidfVectorizer()
tfidf_matrix=tfidf.fit_transform(df['text']).toarray()
tfidf_matrix

array([[0.49681612, 0.        , 0.61366674, 0.61366674, 0.        ],
       [0.8508161 , 0.        , 0.        , 0.52546357, 0.        ],
       [0.        , 0.57735027, 0.57735027, 0.        , 0.57735027],
       [0.49681612, 0.61366674, 0.        , 0.        , 0.61366674]])

In [23]:
print(tfidf.idf_)

[1.22314355 1.51082562 1.51082562 1.51082562 1.51082562]
